---
title: "q201:  life table estimates of relative survival by calendar period of diagnosis using"
format: html
editor: visual
---

```{r}
# Load packages
library(readstata13)
library(dplyr)
library(tidyr)
library(lubridate)
library(relsurv)

# Load melanoma data for limited stages
melanoma <- read.dta13("./data/melanoma.dta") %>% 
  filter(stage == "Localised")

# Load popmort file
popmort <- read.dta13("./data/popmort.dta")
```

```{r}
# Prepare melanoma dataset
melanoma <- melanoma %>% 
  mutate(surv_dd = surv_yy * 365.24,
         status  = if_else(status == "Alive", 0, 1),
         year    = year(dx))
```

```{r}
# Prepare popmort file
popmort_wide <- pivot_wider(popmort,
                            id_cols = c("sex", "_age"),
                            names_from  = "_year",
                            values_from = "prob")

popmort_males <- popmort_wide %>% 
  filter(sex == 1)            %>% 
  select(-c("sex", "_age"))   %>% 
  as.matrix()

popmort_females <- popmort_wide %>% 
  filter(sex == 2)              %>% 
  select(-c("sex", "_age"))     %>% 
  as.matrix()

ratetable <- transrate(popmort_males,
                       popmort_females,
                       yearlim = c(1951, 2000),
                       int.length = 1)
```

```{r}
PP_survfit <- rs.surv(Surv(surv_dd, status)~ sex,
                      data      = melanoma,
                      ratetable = ratetable,
                      method    = "pohar-perme",
                      precision = 10,
                      add.times = seq(1, 1, 365.24 * 10),
                      rmap      = list(age = age * 365.24))
```

```{r}
plot(PP_survfit) # This looks a little bit strange to me
```
